import * as xlsx from 'xlsx'
import { financeDb as db } from './tx'
import { auditLogs } from '@/drizzle/schema'

/**
 * Sanitizes a string for safe spreadsheet export, preventing CSV injection.
 * Prepend with a single quote if it starts with =, +, -, @, \t, or \r.
 */
export function sanitizeSpreadsheetText(value: any): string {
  if (value === null || value === undefined) return ''
  const str = String(value)
  if (/^[=+\-@\t\r]/.test(str)) {
    return `'${str}`
  }
  return str
}

export interface ExportMetadata {
  title: string
  period?: string
  generatedAt?: string
  generatedBy?: string
  filters?: Record<string, string>
}

/**
 * Generates an XLSX buffer safely with metadata headers and sanitized tabular data.
 * @param data Array of objects representing the rows. Will be sanitized automatically if strings.
 * @param metadata Report metadata to inject at the top.
 */
export function generateSafeXlsx(data: Record<string, any>[], metadata: ExportMetadata): Buffer {
  const wb = xlsx.utils.book_new()
  
  // 1. Prepare Metadata Sheet Data
  const sheetData: any[][] = []
  sheetData.push(['Mahabbah Finance'])
  sheetData.push(['Report Title', metadata.title])
  if (metadata.period) sheetData.push(['Period / As-of', metadata.period])
  
  const generatedAt = metadata.generatedAt || new Date().toISOString()
  sheetData.push(['Generated At', generatedAt])
  if (metadata.generatedBy) sheetData.push(['Generated By', metadata.generatedBy])
  
  if (metadata.filters && Object.keys(metadata.filters).length > 0) {
    sheetData.push(['Applied Filters'])
    for (const [k, v] of Object.entries(metadata.filters)) {
      sheetData.push([`  ${k}`, sanitizeSpreadsheetText(v)])
    }
  }
  sheetData.push([]) // empty row separator

  // 2. Prepare Data Headers
  if (data.length > 0) {
    const headers = Object.keys(data[0])
    sheetData.push(headers)

    // 3. Prepare Data Rows (Sanitized)
    for (const row of data) {
      const rowData = headers.map(h => {
        const val = row[h]
        if (typeof val === 'string') return sanitizeSpreadsheetText(val)
        // Keep precise bigints as exact string to avoid floating point truncation
        if (typeof val === 'bigint') return val.toString()
        return val
      })
      sheetData.push(rowData)
    }
  } else {
    sheetData.push(['No data available'])
  }

  const ws = xlsx.utils.aoa_to_sheet(sheetData)
  
  // Auto-width for columns (simple heuristic)
  const wscols = []
  if (data.length > 0) {
      const headers = Object.keys(data[0])
      for (let i = 0; i < headers.length; i++) {
          wscols.push({ wch: Math.max(headers[i].length + 5, 15) })
      }
  } else {
      wscols.push({ wch: 30 }, { wch: 30 })
  }
  ws['!cols'] = wscols
  
  xlsx.utils.book_append_sheet(wb, ws, 'Report')
  
  const buffer = xlsx.write(wb, { type: 'buffer', bookType: 'xlsx' })
  return buffer
}

export async function logExportAudit(userId: number, reportType: string, metadata: ExportMetadata, rowCount: number) {
  await db.insert(auditLogs).values({
    actorUserId: userId,
    action: 'FINANCE_REPORT_EXPORT',
    entityType: 'REPORT',
    metadata: {
      report_type: reportType,
      format: 'XLSX',
      filters: metadata.filters || {},
      row_count: rowCount
    }
  })
}
